name: Development check

on:
  push:
    branches:
      - dev

jobs:
  check-quality-and-build:
    runs-on: ${{ matrix.os }}
    name: Check quality and build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12, 14]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: Check code
      run: yarn lint --max-warnings=0

    - name: Check unit test
      run: yarn test:unit

    - name: Build
      run: yarn build
