name: Development check

on:
  push:
    branches:
      - dev

jobs:
  check-quality-and-build:
    runs-on: ${{ matrix.os }}
    name: Check quality and build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12, 14]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: Check code
      run: yarn lint --max-warnings=0

    - name: Check unit test
      run: yarn test:unit

    - name: Build
      run: yarn build

  deploy:
    runs-on: ubuntu-latest
    name: Deploy development
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: Check code
      run: yarn lint --max-warnings=0

    - name: Check unit test
      run: yarn test:unit

    - name: Build
      run: yarn build
jobs:
  check-quality-and-build-preview:
    runs-on: ubuntu-latest
    name: Check quality and build
    steps:
    - uses: actions/checkout@v2

    - uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - name: Check type
      run: yarn type

    - name: Check code
      run: yarn lint

    - name: Check unit test
      run: yarn test:unit

    - name: Build
      run: yarn build:report

    - uses: actions/upload-artifact@v2
      with:
        name: dist-preview
        path: dist/

    - name: Deploy to ftp
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: ${{ secrets.FTP_PORT }}
        LOCAL_DIR: dist
        REMOTE_DIR: /www/d2-advance/preview-dev
        ARGS: --delete --verbose --parallel=100
